name: pranayama_app
description: App per esercizi di pranayama con round personalizzati.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  audioplayers: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/inhale.mp3
    - assets/sounds/hold.mp3
    - assets/sounds/exhale.mp3
    - assets/predefined_exercises.json
